/* eslint-disable quotes */
export const theme = {
	colors: {
		primary: '#7395B8',
		secondary: '#dc143c',
		action: '#81AE85',
		white: '#FFFFFF',
		medium: '#E3DEFF',
		dark: '#161421',
	},
	actionsColors: {
		primary: '#4B9DB8',
		secondary: '#AD1E02',
		action: '#4CAD70',
		medium: '#B77BB8',
		dark: '#10009E',
	},
	fonts: {
		family: {
			default: "'Open Sans', sans-serif",
			secundary: "'Montserrat',sans-serif",
		},
		sizes: {
			xsmall: '0.8rem',
			small: '1.6rem',
			medium: '2.4rem',
			large: '3.2rem',
			xlarge: '4.0rem',
			xxlarge: '4.8rem',
			huge: '5.6rem',
			xhuge: '6.4rem',
		},
	},
	medias: {
		mobileS: '(max-width: 320px)',
		mobileM: '(max-width: 375px)',
		mobileL: '(max-width: 425px)',
		tablet: '(max-width: 768px)',
		laptop: '(max-width: 1024px)',
		laptopL: '(max-width: 1440px)',
		desktop: '(max-width: 2560px)',
	},
	spacings: {
		xsmall: '0.8rem',
		small: '1.6rem',
		medium: '2.4rem',
		large: '3.2rem',
		xlarge: '4.0rem',
		xxlarge: '4.8rem',
		huge: '5.6rem',
		xhuge: '6.4rem',
	},
	paddings: {
		xsmall: '0.8rem',
		small: '1.6rem',
		medium: '2.4rem',
		large: '3.2rem',
		xlarge: '4.0rem',
		xxlarge: '4.8rem',
		huge: '5.6rem',
		xhuge: '6.4rem',
	},
};
